name: blender-fake-addon

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        blender-version: ["2.78c", "2.79b", "2.80", "2.81", "2.82", "2.83"]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        cd $GITHUB_WORKSPACE
        python --version
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/scripts/requirements.txt
        yolk -l
    - name: Set up Blender ${{ matrix.blender-version }}
      run: |
        cd $GITHUB_WORKSPACE
        sudo apt update
        sudo apt install -f -y blender
        python $GITHUB_WORKSPACE/scripts/get_blender.py ${{ matrix.blender-version }}
    - name: Test Blender ${{ matrix.blender-version }} with pytest
      run: |
        cd $GITHUB_WORKSPACE
        python $GITHUB_WORKSPACE/scripts/run_blender.py ${{ matrix.blender-version }}
